### ISSUE TITLE
FFT fails on Signal2Ds

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#112]
As the title says. Terminal returns the following error:

```python
s = hs.signals.Signal2D(sc.misc.face()).as_signal2D((2,0)).inav[0]
s.plot()
# Call the FFT function from the menu
```

Error: 
```
Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/plugins/fft.py", line 167, in fft
    for i in do_ffts():
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/plugins/fft.py", line 149, in do_ffts
    if u.endswith('-1'):
AttributeError: '_Undefined' object has no attribute 'endswith'
```

**Comment by vidartf** [comment]
Duplicate of #95.

**Comment by thomasaarholt** [comment]
Sorry, should have searched. Thought I was up to date on the issues.
