### ISSUE TITLE
Save figure doesn't do anything

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#118]
The Save Figure option from the file menu does not do anything at all

**Comment by vidartf** [comment]
Any useful errors in the console?

**Comment by thomasaarholt** [comment]
I'm running this from hyperspyui.exe and don't get a terminal reporting errors. The console doesn't show anything when trying to save figure.

**Comment by thomasaarholt** [comment]
Hang on, might be because the signal is

**Comment by vidartf** [comment]
Citing the docs: 
 > If you’ve not launched it with a terminal, the log is attempted written to the folder of hyperspyui. If that location is noe writable, the log file is attempted written to the users home folder (OS dependent). In either case, the log file is named hyperspyui.log.

**Comment by thomasaarholt** [comment]
*bows head to the mighty docs*
Here we go:
```python
--- Logging error ---
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\logging\__init__.py", line 983, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\hyperspyui.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\programdata\miniconda3\lib\site-packages\hyperspyui\__main__.py", line 116, in main
    from hyperspyui.mainwindow import MainWindow
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\programdata\miniconda3\lib\site-packages\hyperspyui\mainwindow.py", line 34, in <module>
    from hyperspyui.mainwindowhyperspy import MainWindowHyperspy, tr
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\programdata\miniconda3\lib\site-packages\hyperspyui\mainwindowhyperspy.py", line 45, in <module>
    from . import hooksignal
  File "<frozen importlib._bootstrap>", line 1016, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\programdata\miniconda3\lib\site-packages\hyperspyui\hooksignal.py", line 24, in <module>
    import hyperspy.signal
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\programdata\miniconda3\lib\site-packages\hyperspy\signal.py", line 35, in <module>
    from hyperspy.drawing import mpl_hie, mpl_hse, mpl_he
  File "<frozen importlib._bootstrap>", line 1016, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\programdata\miniconda3\lib\site-packages\hyperspy\drawing\mpl_hie.py", line 19, in <module>
    from hyperspy.drawing import image, utils
  File "<frozen importlib._bootstrap>", line 1016, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\programdata\miniconda3\lib\site-packages\hyperspy\drawing\image.py", line 27, in <module>
    from hyperspy.gui.tools import ImageContrastEditor
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\programdata\miniconda3\lib\site-packages\hyperspy\gui\__init__.py", line 37, in <module>
    _logger.debug('Loading hyperspy.gui')
Message: 'Loading hyperspy.gui'
Arguments: ()
```

**Comment by vidartf** [comment]
Assumed fixed in master, reopen if it reappears.
