### ISSUE TITLE
Having issue with logger.

### ISSUE THREAD

**Issue by erh3cq** [hyperspy/hyperspyUI#141]
On loading UI:
```
    H y p e r S p y
    Version 1.3+dev

    http://www.hyperspy.org

    Python 3.6.1 | packaged by conda-forge | (default, May  2 2017, 22:29:14) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Eric Hoglund\Anaconda3\envs\data-analysis\lib\logging\__init__.py", line 994, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\ERICHO~1\Documents\GitHub\hyperspyUI\build\lib\hyperspyui\__main__.py", line 137, in <module>
    main()
  File "C:\Users\ERICHO~1\Documents\GitHub\hyperspyUI\build\lib\hyperspyui\__main__.py", line 118, in main
    form = MainWindow()
  File "c:\users\ericho~1\documents\github\hyperspyui\hyperspyui\mainwindow.py", line 104, in __init__
    logger.info("Main window loaded!")
Message: 'Main window loaded!'
Arguments: ()
```

On loading a signal i get a huge output of logging errors as well.  I will not copy them here, because they go on for pages :). Any clues? I am running in conda through an environment "data-analysis"

Thanks
Eric

**Comment by vidartf** [comment]
Hmm. How do you launch the UI?

**Comment by erh3cq** [comment]
Through the desktop icon.
target: "C:\Users\Eric Hoglund\Anaconda3\envs\data-analysis\pythonw.exe" "C:\Users\ERICHO~1\Documents\GitHub\hyperspyUI\build\lib\hyperspyui\__main__.py"
Start in: C:\Users\ERICHO~1\Anaconda3\envs\data-analysis

**Comment by erh3cq** [comment]
Also only seems to be a thing when I have output to console in settings
