### ISSUE TITLE
moviesaver error on ui startup

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#142]
This is a low-priority issue.
On Windows, loading hyperspyui by `python -m hyperspyui`

In the terminal window the following error appears:
```python
INFO:hyperspy.io_plugins.bcf:The fast cython based bcf unpacking library were found
DEBUG:hyperspyui:Initializing plugins
C:\ProgramData\Miniconda3\lib\site-packages\hyperspyui\plugins\moviesaver.py:42: UserWarning: MovieWriter ffmpeg unavailable
  warnings.warn("MovieWriter %s unavailable" % writer)
C:\ProgramData\Miniconda3\lib\site-packages\hyperspyui\pluginmanager.py:131: RuntimeWarning: Exception in import of hyperspyui plugin "moviesaver" error:
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperspyui\pluginmanager.py", line 128, in discover
    __import__('hyperspyui.plugins.' + plug, globals())
  File "C:\ProgramData\Miniconda3\lib\site-packages\hyperspyui\plugins\moviesaver.py", line 47, in <module>
    raise ValueError("Cannot save animation: no writers are "
ValueError: Cannot save animation: no writers are available. Please install mencoder or ffmpeg to save animations.

  self.warn("import", plug)
```

**Comment by vidartf** [comment]
Yes, for that plugin to work it needs ffmpeg/mencoder (optional dependencies if you'd like). If that is not available, it prevents itself from loading by throwing an exception (plugin load exceptions are then converted to warnings by the plugin manager). Maybe you are saying that it should do something a little less aggressive (i.e. a less angry log message)?

**Comment by ericpre** [comment]
This should be partially solved with the conda recipe on conda-forge. Not sure if this will be straightforward to add ffmpeg as optional dependency.
