### ISSUE TITLE
Gaussian smooth fails with float32 in specific case

### ISSUE THREAD

**Issue by blazzter** [hyperspy/hyperspyUI#145]
if I have object:

```
In [31]: data = ui.get_selected_signal()
In [32]: data
Out[32]: <Signal2D, title: , dimensions: (100, 100|128, 128)>
```

and do:
```
In [34]: npdata = np.array(data)
In [35]: frame = npdata[10,10,:,:]
In [36]: frame.dtype
Out[36]: dtype('float32')

In [37]: hsframe = hs.signals.Signal2D(frame)
In [38]: hsframe.plot()
```

and apply Gaussian filter, it fails with:

> Traceback (most recent call last):
>   File "/home/mkrajnak/.local/lib/python3.5/site-packages/hyperspyui/plugins/gaussianfilter.py", line 198, in set_preview
>     self.update()
>   File "/home/mkrajnak/.local/lib/python3.5/site-packages/hyperspyui/plugins/gaussianfilter.py", line 216, in update
>     record=False, out=out)
>   File "/home/mkrajnak/.local/lib/python3.5/site-packages/hyperspyui/plugins/gaussianfilter.py", line 112, in gaussian
>     im_o[:] = gaussian(im_i, sigma, *args, **kwargs)
>   File "/home/mkrajnak/.local/lib/python3.5/site-packages/skimage/filters/_gaussian.py", line 118, in gaussian
>     image = convert_to_float(image, preserve_range)
>   File "/home/mkrajnak/.local/lib/python3.5/site-packages/skimage/_shared/utils.py", line 243, in convert_to_float
>     image = img_as_float(image)
>   File "/home/mkrajnak/.local/lib/python3.5/site-packages/skimage/util/dtype.py", line 336, in img_as_float
>     return convert(image, np.float64, force_copy)
>   File "/home/mkrajnak/.local/lib/python3.5/site-packages/skimage/util/dtype.py", line 236, in convert
>     raise ValueError("Images of type float must be between -1 and 1.")
> ValueError: Images of type float must be between -1 and 1.

If I just create a random np.random.randr  image this does not happen, any clue?

**Comment by francisco-dlp** [comment]
I think that you've found a bug: in order to make the data palatable for skimage's gaussian filter, the plugin normalises the data making the (wrong) assumption that vmax - vmin > 1.

This can be easily fixed but, @vidartf. why not using ndimage's gaussian filter instead which doesn't require renormalising the images?

**Comment by vidartf** [comment]
> why not using ndimage's gaussian filter instead which doesn't require renormalising the images?

If I remember correctly, this might have been a performance issue. The blur should be fast in order to give be responsive when interactively changing the sigma.
