### ISSUE TITLE
hyperspyUI not working from pip

### ISSUE THREAD

**Issue by matkraj** [hyperspy/hyperspyUI#149]
After clean install in archlinux, hyperspyui is not working.
I tried quite a lot of combinations for qt background, but nothing seems to work.
Fails with:

```python
INFO:hyperspy.io_plugins.bcf:The fast cython based bcf unpacking library were found
Traceback (most recent call last):
  File "/usr/bin/hyperspyui", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/hyperspyui/__main__.py", line 116, in main
    from hyperspyui.mainwindow import MainWindow
  File "/usr/lib/python3.6/site-packages/hyperspyui/mainwindow.py", line 34, in <module>
    from hyperspyui.mainwindowhyperspy import MainWindowHyperspy, tr
  File "/usr/lib/python3.6/site-packages/hyperspyui/mainwindowhyperspy.py", line 41, in <module>
    from .mainwindowutillayer import MainWindowActionRecorder, tr
  File "/usr/lib/python3.6/site-packages/hyperspyui/mainwindowutillayer.py", line 24, in <module>
    from .mainwindowbase import MainWindowBase, tr
  File "/usr/lib/python3.6/site-packages/hyperspyui/mainwindowbase.py", line 39, in <module>
    import hyperspyui.mdi_mpl_backend
  File "/usr/lib/python3.6/site-packages/hyperspyui/mdi_mpl_backend.py", line 45, in <module>
    from matplotlib.backends.backend_qt5 import (SPECIAL_KEYS, SUPER, ALT, CTRL,
ImportError: cannot import name 'fn_name'
```

**Comment by ricounet67** [comment]
same for me under mac osx 10.12 and a clean anaconda install

**Comment by vidartf** [comment]
I was able to solve this by version pinning some dependencies. This is necessary since traitsui/pyface still do not support PyQt 5 (while other dependencies are pushing for an upgrade of PyQt).

Solution with conda:
```
conda install pyqt=4
pip install hyperspy_gui_traitsui
```

If you do not have conda, you will have to ensure PyQt4 is installed. The conda version seems to insist on matplotlib < 2. Not sure if this is a general requirement, or only for the conda builds.

**Comment by matkraj** [comment]
I works with:
- downgrading matplotlib in pip `pip install matplotlib==1.5.3
`
- removing any qt from pip
- install pyqt4 form system repositories

**Comment by vidartf** [comment]
Thanks for the feedback! Closing for now.

**Comment by matkraj** [comment]
just a note: this also solved problems with hyperspy .plot() where qt was giving 1000s of errors
