### ISSUE TITLE
AttributeError: module 'PyQt5.QtGui' has no attribute 'QApplication'

### ISSUE THREAD

**Issue by jinglong485** [hyperspy/hyperspyUI#158]
After installing hyperspyui and run "python -m hyperspyui", an error pops up: 
Traceback (most recent call last):
  File "/Users/jinglong/.pyenv/versions/3.6.6rc1/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jinglong/.pyenv/versions/3.6.6rc1/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jinglong/.pyenv/versions/3.6.6rc1/envs/hyperui/lib/python3.6/site-packages/hyperspyui/__main__.py", line 137, in <module>
    main()
  File "/Users/jinglong/.pyenv/versions/3.6.6rc1/envs/hyperui/lib/python3.6/site-packages/hyperspyui/__main__.py", line 77, in main
    from hyperspyui.singleapplication import get_app
  File "/Users/jinglong/.pyenv/versions/3.6.6rc1/envs/hyperui/lib/python3.6/site-packages/hyperspyui/singleapplication.py", line 30, in <module>
    class SingleApplication(QtGui.QApplication):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QApplication'

What should I do?

**Comment by jat255** [comment]
Confirming this problem installing on Arch Linux in a miniconda Python 3.6 environment

**Comment by jat255** [comment]
This error is because there has not been a release pushed to pypi.org since the update to Qt5. 

@jinglong485 in the meantime as a workaround, try the following:

```
pip uninstall hyperspyui
pip install git+git://github.com/hyperspy/hyperspyUI.git  
```

This will require that you have the latest dependencies installed, such as an up-to-date HyperSpy (1.3.2+), traitsui and pyface (both 6.0.0), Qt (5.2+). Let me know how you make out.

**Comment by jinglong485** [comment]
The development version works! Thank you!
