### ISSUE TITLE
Installing HyperspyUI on Mac via Pip

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#62]
```shell
thomas$ pip install hyperspyui
Collecting hyperspyui
  Downloading hyperspyUI-0.6.1-py3-none-any.whl (597kB)
    100% |████████████████████████████████| 598kB 450kB/s
Requirement already satisfied (use --upgrade to upgrade): traitsui in /Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages (from hyperspyui)
Collecting python-qt-binding (from hyperspyui)
  Using cached python_qt_binding-0.2.17.tar.gz
Requirement already satisfied (use --upgrade to upgrade): hyperspy>=0.8.1 in /Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages (from hyperspyui)
Collecting pyqode.python>=2.6.0 (from hyperspyui)
  Downloading pyqode.python-2.8.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 49kB 5.1MB/s
Collecting pywin32 (from hyperspyui)
  Could not find a version that satisfies the requirement pywin32 (from hyperspyui) (from versions: )
No matching distribution found for pywin32 (from hyperspyui)
```

It attempts to collect pywin32, which doesn't work on Mac (as the name implies). How is it installed on Linux? I was attempting to follow the Quickstart guide.

**Comment by vidartf** [comment]
Oh. That's a mistake on my part. It currently only checks the platform when creating the wheel (which I created on Windows), instead of on the install. If you are on python 3 (your output seems to indicate that), you should be able to work around it by supplying the option `--no-binary hyperspyui` to pip, i.e. `pip install --no-binary hyperspyui hyperspyui`. This should force a source install.

**Comment by thomasaarholt** [comment]
Yep, that solved the problem.

Unfortunately, I don't seem to be able to run it.

Running 
```python
python -m hyperspyui.launch
```
gives me an error I can't really interpret:
```python
Traceback (most recent call last):
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/launch.py", line 130, in <module>
    main()
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/launch.py", line 87, in main
    if settings['allow_multiple_instances', bool]:
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/settings.py", line 59, in __getitem__
    ret = ("true" == ret.lower())
AttributeError: 'bool' object has no attribute 'lower'
```

I initially had matplotlib v2.x installed (developer version, but works nicely with Hyperspy), but used version 1.5.1 to get the above error. I got the following error when I tried running `hyperspyui` with v2, though suspect I'm not supposed to touch `hyperspyui` at all.

```python
Traceback (most recent call last):
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 640, in _build_master
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 941, in require
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 833, in resolve
pkg_resources.ContextualVersionConflict: (matplotlib 2.x (/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages), Requirement.parse('matplotlib>=1.3'), {'hyperspyUI'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thomas/anaconda/envs/c3/bin/hyperspyui", line 5, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 3140, in <module>
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 3126, in _call_aside
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 3153, in _initialize_master_working_set
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 642, in _build_master
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 655, in _build_from_requirements
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 828, in resolve
pkg_resources.DistributionNotFound: The 'matplotlib>=1.3' distribution was not found and is required by hyperspyUI
```

**Comment by vidartf** [comment]
The UI has not been tested with MPL 2, so I can't help you there, but the first error I think is Qt dependent. Which version of Qt do you use (PyQt4, PyQt5 or PySide)?

**Comment by vidartf** [comment]
This should be fixed in #64. I packaged a wheel from that branch that I attached here. Could you test it? (I had to zip the wheel to get github to accept the filetype, so just unzip it and run `pip install ./path_to_wheel.whl`:
[hyperspyUI-0.7+dev-py3-none-any.zip](https://github.com/hyperspy/hyperspyUI/files/183297/hyperspyUI-0.7.dev-py3-none-any.zip)

**Comment by thomasaarholt** [comment]
That worked fine! It installed without problem. That said, does hyperspyui support python3?

**Comment by vidartf** [comment]
Same issue as previously, to which I asked which version of Qt you use (PyQt4, PyQt5 or PySide). I'm pretty sure I know the fix, but want to make sure.

**Comment by vidartf** [comment]
To check, run the following
```python
import python_qt_binding
print(python_qt_binding.QT_BINDING)
```

**Comment by thomasaarholt** [comment]
Shit, sorry about that. I'm very obviously on holiday.

This is the result of the qt_binding:

```python
>>> import python_qt_binding
>>> print(python_qt_binding.QT_BINDING)
pyqt
```

**Comment by vidartf** [comment]
Could you give me `python_qt_binding.QT_BINDING_VERSION` as well?

**Comment by thomasaarholt** [comment]
4.11.4

**Comment by vidartf** [comment]
Should work on master now.

**Comment by thomasaarholt** [comment]
It does. The GUI opens up, but I get a series of import errors. 

It's more important that it's able to run on Linux, so I think I'll say **disregard the following**, unless you have some spare time, enjoy pain or think there are some quick fixes.

As said, the GUI opens, but the terminal returns a bunch of errors (seen below). Interestingly, I can load files using the console, and plotting it works well. As far as I can tell (played around for ten minutes), everything else works well as well, except opening files using the file menu or the open button.

The rest I'm very impressed with! +1: 

```
(c3)Thomas-Macbook-Pro:0_Hyperspy thomas$ python -m hyperspyui.launch
/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/pluginmanager.py:110: RuntimeWarning: Exception in import of hyperspyui plugin "linemeasure" error:
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/plugins/linemeasure.py", line 27, in <module>
    from hyperspy.roi import BaseInteractiveROI
ImportError: No module named 'hyperspy.roi'

  self.warn("import", plug)
/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/pluginmanager.py:110: RuntimeWarning: Exception in import of hyperspyui plugin "align" error:
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/plugins/align.py", line 25, in <module>
    from hyperspyui.tools import SelectionTool
ImportError: cannot import name 'SelectionTool'

  self.warn("import", plug)
/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/pluginmanager.py:110: RuntimeWarning: Exception in import of hyperspyui plugin "dmannotations" error:
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/plugins/dmannotations.py", line 4, in <module>
    from hyperspy.drawing.widgets import LabelWidget
ImportError: cannot import name 'LabelWidget'

  self.warn("import", plug)
/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/pluginmanager.py:110: RuntimeWarning: Exception in import of hyperspyui plugin "fitting" error:
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/plugins/fitting.py", line 30, in <module>
    from hyperspyui.tools import SelectionTool
ImportError: cannot import name 'SelectionTool'

  self.warn("import", plug)
/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/plugins/moviesaver.py:42: UserWarning: MovieWriter ffmpeg unavailable
  warnings.warn("MovieWriter %s unavailable" % writer)
/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/pluginmanager.py:110: RuntimeWarning: Exception in import of hyperspyui plugin "croptool" error:
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/plugins/croptool.py", line 29, in <module>
    from hyperspy.roi import BaseInteractiveROI
ImportError: No module named 'hyperspy.roi'

  self.warn("import", plug)
/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/pluginmanager.py:110: RuntimeWarning: Exception in import of hyperspyui plugin "segmentation" error:
  File "/Users/thomas/anaconda/envs/c3/lib/python3.5/site-packages/hyperspyui/plugins/segmentation.py", line 23, in <module>
    from hyperspyui.tools import MultiSelectionTool
ImportError: cannot import name 'MultiSelectionTool'

  self.warn("import", plug)
`
``

**Comment by vidartf** [comment]
These warnings are related to "missing" features in your version of hyperspy: The UI is designed to work with the current development version of HyperSpy (what will become v1.0). If these features are missing (say in 0.8.x) it will attempt to run as best as it can, to enable you to do as much as possible, but no guarantees are made, and a lot of useful features simply won't work. Plugins that fail to load because of missing features will simply not add their menu/toolbar entries, or their widgets.

**Comment by thomasaarholt** [comment]
Aha! Very good ;)

I'll have another go then. This looks good.
