### ISSUE TITLE
Cannot open file using GUI or menu

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#76]
On Mac.
I get the following warning in the terminal:

``` python
Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/mainwindowhyperspy.py", line 511, in load
    filenames = self.prompt_files(type_choices)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/mainwindowutillayer.py", line 314, in prompt_files
    self, title, path, extension_filter)
TypeError: getOpenFileNames(parent: QWidget = None, caption: object = '', directory: object = '', filter: object = '', options: QFileDialog.Options = 0): argument 3 has unexpected type 'QPyNullVariant'
```

**Comment by vidartf** [comment]
Does your log say anything about whether you are using PyQt4 or PySide (alternatively, could you check which of those you have installed)?

**Comment by thomasaarholt** [comment]
I'm unsure of how to check. In the hyperspyui console:
`import PyQt4` works fine
```import PySide
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5d84305db498> in <module>()
----> 1 import PySide

/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/qtconsole/qt_loaders.py in load_module(self, fullname)
     53     Importing %s disabled by QtConsole, which has
     54     already imported an incompatible Qt Binding: %s
---> 55     """ % (fullname, loaded_api()))
     56 
     57 ID = ImportDenier()

ImportError: 
    Importing PySide disabled by QtConsole, which has
    already imported an incompatible Qt Binding: pyqt
```

**Comment by thomasaarholt** [comment]
WOW I CAN DRAG AND DROP

**Comment by vidartf** [comment]
Yeah, drag and drop should work, and you can also pass filenames as arguments to the launch command. If you already have a running UI, and you run the launch command again with file name arguments, those files should open in the existing instance (although that behaviour can be changed in the settings).

**Comment by vidartf** [comment]
Quick check for error: can you open the settings and put a valid directory into the "current directory" (or similar)?

**Comment by thomasaarholt** [comment]
I can't open the settings window (from the `Windows` menu bar item). Terminal reports:

```python
Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/mainwindowbase.py", line 358, in edit_settings
    d = SettingsDialog(self, self)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/widgets/settingsdialog.py", line 55, in __init__
    self.create_controls()
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/widgets/settingsdialog.py", line 271, in create_controls
    self._add_groups(s)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/widgets/settingsdialog.py", line 186, in _add_groups
    tab = self._create_settings_widgets(settings)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/widgets/settingsdialog.py", line 155, in _create_settings_widgets
    w.setRange(np.iinfo(np.float32).min, np.iinfo(np.float32).max)
  File "/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/numpy/core/getlimits.py", line 254, in __init__
    raise ValueError("Invalid integer data type.")
ValueError: Invalid integer data type.
```

**Comment by thomasaarholt** [comment]
But I have set the current working directory by 
```python
import os
os.chdir(path)
```
The errors are still present with that set to a known path.

**Comment by thomasaarholt** [comment]
Btw, the `python -m hyperspyui.launch` command did not work on my mac. `hyperspyui` does.
```python
 No module named hyperspyui.launch
```

**Comment by vidartf** [comment]
Yeah, the `launch` submodule was discontinued.

**Comment by vidartf** [comment]
I've split the settings dialog issue into #79.
