### ISSUE TITLE
Menu actions "Decompose" and "BSS" run forever

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#78]
Running these on line scans that are 20x2000 pixels in size. Below is the traceback from the terminal.

Sorry about all the issue reporting - figured I'd do this whilst I'm playing around.

``` python
Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/threaded.py", line 56, in process
    self.run_function()
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/plugins/mva.py", line 226, in do_threaded
    ns.s = self._do_decomposition(ns.s, algorithm=algorithm)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/plugins/mva.py", line 191, in _do_decomposition
    s.decomposition()
  File "/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/hyperspy/learn/mva.py", line 244, in decomposition
    auto_transpose=auto_transpose)
  File "/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/hyperspy/learn/svd_pca.py", line 82, in svd_pca
    U, S, V = scipy.linalg.svd(data, full_matrices=False)
  File "/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/scipy/linalg/decomp_svd.py", line 96, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/scipy/_lib/_util.py", line 226, in _asarray_validated
    raise ValueError('masked arrays are not supported')
```

**Comment by thomasaarholt** [comment]
Strange. The error was reported on a core loss EELS signal that had been deconvoluted. But testing now on the low-loss it is fine.

**Comment by vidartf** [comment]
I think this can be translated to: If MVA process fails, close progress window. ?
