### ISSUE TITLE
Save button not working

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#82]
Trying to save a normal image:
```python
DEBUG:hyperspyui.mainwindowhyperspy:entering save(), with args: None, None
DEBUG:hyperspyui.mainwindowhyperspy:No signals passed, saving selection: [<hyperspyui.signalwrapper.SignalWrapper object at 0x13cb301f8>]
DEBUG:hyperspyui.mainwindowhyperspy:Save type choices: All types (*.*);;*.ppm;;*.he5;;*.bmp;;*.csv;;*.emsa;;*.h5;;*.hdf5;;*.emd;;*.bcf;;*.hdf;;*.tif;;*.blo;;*.he4;;*.ser;;*.jpeg;;*.pcx;;*.pgm;;*.spi;;*.gif;;*.png;;*.msp;;*.mas;;*.msa;;*.jpe;;*.ems;;*.pbm;;*.dib;;*.dm3;;*.tiff;;*.dens;;*.hdf4;;*.jpg;;*.emi;;*.mrc;;*.xbm;;*.ali;;*.unf;;*.dm4;;*.rpl;;*.h4;;*.nc
Traceback (most recent call last):
  File "/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/hyperspyui/mainwindowhyperspy.py", line 576, in save
    path_suggestion = self.get_signal_filepath_suggestion(s)
  File "/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/hyperspyui/mainwindowhyperspy.py", line 609, in get_signal_filepath_suggestion
    base = os.path.dirname(self.cur_dir)
  File "/Users/thomas/anaconda/envs/sims/lib/python3.5/posixpath.py", line 148, in dirname
    i = p.rfind(sep) + 1
AttributeError: 'QPyNullVariant' object has no attribute 'rfind'
```

**Comment by vidartf** [comment]
Seems that again the `cur_dir` variable has a value it did not expect, similarly to #76 .
