### ISSUE TITLE
Line Measure error

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#84]
Trying to use the Line measure (ruler) tool to measure the distance on a DF image. Button is pressed, but this happens when I then click on the image:

```python
Traceback (most recent call last):
  File "/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 259, in mousePressEvent
    guiEvent=event)
  File "/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 1903, in button_press_event
    self.callbacks.process(s, mouseevent)
  File "/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/_tools/linetool.py", line 95, in on_mousedown
    axes = self._get_axes(event)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/_tools/signalfiguretool.py", line 62, in _get_axes
    if self._is_sig(event):
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/_tools/signalfiguretool.py", line 53, in _is_sig
    if sw.signal._plot.signal_plot is not None:
AttributeError: 'NoneType' object has no attribute 'signal_plot'
```

**Comment by vidartf** [comment]
Hmm.. It seems it might have lost track of which plots belong to which signal. Are you able to reproduce this reliably? If so, what are the steps you need to take in order to reproduce?

**Comment by thomasaarholt** [comment]
Interestingly, after restarting hyperspyui I am unable to reproduce it, with the same file.

Thomas Aarholt
thomasaarholt@gmail.com

**Comment by vidartf** [comment]
The UI has to track the signals, and their association with figures, so if there is a lot going on, this tracking state might sometimes become corrupted. A restart will almost always solve this.

**Comment by thomasaarholt** [comment]
I realised my error. I was calling matplotlib to plot an image separately, and then went "ooh, I wonder if I can measure the length using this"...

You're in the clear, my bad.

**Comment by vidartf** [comment]
Maybe a helpful error message would be an improvement

**Comment by thomasaarholt** [comment]
That might be good - it'll raise awareness of how the tools can be used on UI-produced images and not on ones produced by say, `plt.imshow()`. Whilst I understand the (obvious) reason why, it might not be as obvious to someone who is inexperience with python - which is perhaps the target audience of the UI.
