### ISSUE TITLE
Axes order window bugs

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#91]
The up and down arrows present on the attached image yield the error at the bottom of this post. I don't know what they do, but if they navigate through the signal then they are most welcome. 

In addition, the "reverse axes" button does not do anything, and doesn't report an error. For info, a bug where the hyperspy transpose doesn't work as intended could affect it: (https://github.com/hyperspy/hyperspy/issues/1387).

<img width="176" alt="screenshot 2017-01-18 13 20 17" src="https://cloud.githubusercontent.com/assets/2721423/22065610/f6219c1e-dd80-11e6-91a8-701494ebf909.png">

```python
Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/plugins/axesorderwidget.py", line 179, in _move_down
    self._move_item(i)
  File "/Users/thomas/Dropbox/0_Git/GitHub/hyperspyUI/hyperspyui/plugins/axesorderwidget.py", line 135, in _move_item
    ax = item.data(QtCore.Qt.UserRole)
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by vidartf** [comment]
This has received very little love. The buttons are supposed to change order of axes, including moving from signal to nav space. It should also support drag and drop?

I'll try to look into the exception.
